stages:
- name: buildimage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sebbyflaskapp
      pushRemote: true
      registry: 10.42.0.74:34189
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./heimdall.yaml
timeout: 60
notification: {}
