stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/app:v1
      pushRemote: false
      registry: 127.0.0.1
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./heimdall.yaml
timeout: 60
notification: {}
