stages:
- name: buildimage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sebby/sebbyflaskapp:v1
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./heimdall.yaml
timeout: 60
notification: {}
