apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: default
spec:
    spec:
      containers:
      - image: sebbyflaskapp
        imagePullPolicy: Always
        name: flaskapp
        volumeMounts:
        - mountPath: /config
          name: flaskapp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: flaskapp
        persistentVolumeClaim:
          claimName: heimdall
